version: '3.7'

services:
  backendpost:
    container_name: backendpost
    build:
      context: .
      dockerfile: ./dockerfiles/backend.Dockerfile
    environment:
      - app_env=${docker_env}
    restart: unless-stopped
    networks:
      - host_networkpost
    volumes:
      - ./src/backend:/app
    env_file:
      - ./environment/dev/backend.env
    ports:
      - '1883:1883'
      - '8080:8080'
    depends_on:
      - databasepost
  databasepost:
    container_name: dbpost
    build:
      context: .
      dockerfile: ./dockerfiles/database.Dockerfile
    attach: false
    environment:
      - app_env=${docker_env}
    restart: always
    env_file:
      - ./environment/dev/database.env
    volumes:
      - dbpost:/opt/couchdb/data
    ports:
      - '5984:5984'
    networks:
      - host_networkpost
volumes:
  dbpost:
networks:
  host_networkpost:
    external: true