version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./dockerfiles/backend.Dockerfile
    environment:
      - app_env=${docker_env}
    restart: unless-stopped
    networks:
      - host_network
    volumes:
      - ./src/backend:/app
    env_file:
      - ./environment/dev/backend.env
    ports:
      - '1883:1883'
      - '8080:8080'
    depends_on:
      - database
  database:
    container_name: db
    build:
      context: .
      dockerfile: ./dockerfiles/database.Dockerfile
    attach: false
    environment:
      - app_env=${docker_env}
    restart: always
    env_file:
      - ./environment/dev/database.env
    volumes:
        - db:/opt/couchdb/data
    ports:
      - '5984:5984'
    networks:
      - host_network
volumes:
  db:
networks:
  host_network:
    external: true