openapi: 3.0.3
info:
  contact:
    email: nikita@ttnr.me
  title: Swagger - OpenAPI 3.0
  version: 1.0.0
servers:
- description: Dev server
  url: http://api.template.de/
- description: Prod server
  url: https://euw.backend.example.com/
security:
- bearerAuth: []
tags:
- description: Authenticate device
  name: authentication
- description: Check application health
  name: status
- description: Address device
  name: device
paths:
  /health:
    get:
      operationId: health
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
          description: Health
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
          description: Health
      summary: Check health of server
      tags:
      - status
  /login:
    post:
      requestBody:
        $ref: '#/components/requestBodies/DeviceLogin'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error messages
      summary: User login
      tags:
      - authentication
  /device/change-state:
    post:
      requestBody:
        $ref: '#/components/requestBodies/DeviceChangeState'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error messages
      summary: Modify state of device
      tags:
      - device
  /device/change-options:
    post:
      requestBody:
        $ref: '#/components/requestBodies/DeviceChangeOptions'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error messages
      summary: Modify options of device
      tags:
      - device
components:
  requestBodies:
    DeviceLogin:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeviceLogin'
      description: Device login
    DeviceChangeState:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeviceChangeState'
      description: Change device state
    DeviceChangeOptions:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeviceChangeOptions'
      description: Change device options
  responses:
    Success:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Success'
      description: Success
    Error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Error messages
    Health:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Health'
      description: Health
  schemas:
    Success:
      example:
        warningMessages:
        - code: code
          message: message
        - code: code
          message: message
        messages:
        - code: code
          message: message
        - code: code
          message: message
      properties:
        messages:
          items:
            $ref: '#/components/schemas/Message'
          type: array
        warningMessages:
          items:
            $ref: '#/components/schemas/Message'
          type: array
      type: object
    Error:
      properties:
        warningMessages:
          items:
            $ref: '#/components/schemas/Message'
          type: array
        errorMessages:
          items:
            $ref: '#/components/schemas/Message'
          type: array
      type: object
    Message:
      example:
        code: code
        message: message
      properties:
        code:
          type: string
        message:
          type: string
      type: object
    Health:
      example:
        server: true
        db: true
      properties:
        server:
          type: boolean
        db:
          type: boolean
      type: object
    DeviceChangeState:
      oneOf:
      - $ref: '#/components/schemas/OpenStateOptions'
      - $ref: '#/components/schemas/ClosedStateOptions'
      - $ref: '#/components/schemas/PacktrapStateOptions'
    OpenStateOptions:
      properties:
        state:
          enum:
          - open
          type: string
        emitOpenEvent:
          description: Emit open event
          type: boolean
      required:
      - emitOpenEvent
      - state
      type: object
    ClosedStateOptions:
      properties:
        state:
          enum:
          - closed
          type: string
      required:
      - state
      type: object
    PacktrapStateOptions:
      properties:
        state:
          enum:
          - packtrap
          type: string
        emitPacktrapEvent:
          description: Emit packtrap event
          type: boolean
      required:
      - emitPacktrapEvent
      - state
      type: object
    DeviceLogin:
      example:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      properties:
        token:
          format: application/jwt
          type: string
      required:
      - token
      type: object
    DeviceChangeOptions:
      example:
        wifi:
          password: password
          ssid: ssid
        kafka:
          url: url
        name: name
      properties:
        name:
          type: string
        wifi:
          $ref: '#/components/schemas/DeviceChangeOptions_wifi'
        kafka:
          $ref: '#/components/schemas/DeviceChangeOptions_kafka'
      type: object
    DeviceChangeOptions_wifi:
      example:
        password: password
        ssid: ssid
      properties:
        ssid:
          type: string
        password:
          type: string
      type: object
    DeviceChangeOptions_kafka:
      example:
        url: url
      properties:
        url:
          type: string
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
