/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)

// AuthenticationAPIRouter defines the required methods for binding the api requests to a responses for the AuthenticationAPI
// The AuthenticationAPIRouter implementation should parse necessary information from the http request,
// pass the data to a AuthenticationAPIServicer to perform the required actions, then write the service results to the http response.
type AuthenticationAPIRouter interface {
	LoginPost(http.ResponseWriter, *http.Request)
}

// DeviceAPIRouter defines the required methods for binding the api requests to a responses for the DeviceAPI
// The DeviceAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DeviceAPIServicer to perform the required actions, then write the service results to the http response.
type DeviceAPIRouter interface {
	DeviceChangeOptionsPost(http.ResponseWriter, *http.Request)
	DeviceChangeStatePost(http.ResponseWriter, *http.Request)
}

// StatusAPIRouter defines the required methods for binding the api requests to a responses for the StatusAPI
// The StatusAPIRouter implementation should parse necessary information from the http request,
// pass the data to a StatusAPIServicer to perform the required actions, then write the service results to the http response.
type StatusAPIRouter interface {
	Health(http.ResponseWriter, *http.Request)
}

// AuthenticationAPIServicer defines the api actions for the AuthenticationAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AuthenticationAPIServicer interface {
	LoginPost(context.Context, DeviceLogin, http.ResponseWriter, *http.Request) (ImplResponse, error)
}

// DeviceAPIServicer defines the api actions for the DeviceAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DeviceAPIServicer interface {
	DeviceChangeOptionsPost(context.Context, DeviceChangeOptions, http.ResponseWriter, *http.Request) (ImplResponse, error)
	DeviceChangeStatePost(context.Context, DeviceChangeState, http.ResponseWriter, *http.Request) (ImplResponse, error)
}

// StatusAPIServicer defines the api actions for the StatusAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type StatusAPIServicer interface {
	Health(context.Context) (ImplResponse, error)
}
