/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// StatusAPIService is a service that implements the logic for the StatusAPIServicer
// This service should implement the business logic for every endpoint for the StatusAPI API.
// Include any external packages or services that will be required by this service.
type StatusAPIService struct {
}

// NewStatusAPIService creates a default api service
func NewStatusAPIService() StatusAPIServicer {
	return &StatusAPIService{}
}

// Health - Check health of server
func (s *StatusAPIService) Health(ctx context.Context) (ImplResponse, error) {
	// TODO - update Health with the required logic for this service method.
	// Add api_status_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Health{}) or use other options such as http.Ok ...
	// return Response(200, Health{}), nil

	// TODO: Uncomment the next line to return response Response(500, Health{}) or use other options such as http.Ok ...
	// return Response(500, Health{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Health method not implemented")
}
