/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type OpenStateOptions struct {
	State string `json:"state"`

	// Emit open event
	EmitOpenEvent bool `json:"emitOpenEvent"`
}

// AssertOpenStateOptionsRequired checks if the required fields are not zero-ed
func AssertOpenStateOptionsRequired(obj OpenStateOptions) error {
	return nil
}

// AssertOpenStateOptionsConstraints checks if the values respects the defined constraints
func AssertOpenStateOptionsConstraints(obj OpenStateOptions) error {
	return nil
}
