/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceChangeOptionsKafka struct {
	Url string `json:"url,omitempty"`
}

// AssertDeviceChangeOptionsKafkaRequired checks if the required fields are not zero-ed
func AssertDeviceChangeOptionsKafkaRequired(obj DeviceChangeOptionsKafka) error {
	return nil
}

// AssertDeviceChangeOptionsKafkaConstraints checks if the values respects the defined constraints
func AssertDeviceChangeOptionsKafkaConstraints(obj DeviceChangeOptionsKafka) error {
	return nil
}
