/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceOptionsWifi struct {
	Ssid string `json:"ssid,omitempty"`

	Password string `json:"password,omitempty"`
}

// AssertDeviceOptionsWifiRequired checks if the required fields are not zero-ed
func AssertDeviceOptionsWifiRequired(obj DeviceOptionsWifi) error {
	return nil
}

// AssertDeviceOptionsWifiConstraints checks if the values respects the defined constraints
func AssertDeviceOptionsWifiConstraints(obj DeviceOptionsWifi) error {
	return nil
}
