/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceOptionsKafka struct {
	Url string `json:"url,omitempty"`
}

// AssertDeviceOptionsKafkaRequired checks if the required fields are not zero-ed
func AssertDeviceOptionsKafkaRequired(obj DeviceOptionsKafka) error {
	return nil
}

// AssertDeviceOptionsKafkaConstraints checks if the values respects the defined constraints
func AssertDeviceOptionsKafkaConstraints(obj DeviceOptionsKafka) error {
	return nil
}
