/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OpenStateOptions { 
    state: OpenStateOptions.StateEnum;
    /**
     * Emit open event
     */
    emitOpenEvent: boolean;
}
export namespace OpenStateOptions {
    export type StateEnum = 'open';
    export const StateEnum = {
        Open: 'open' as StateEnum
    };
}